
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar/AppSidebar";
import { Navbar } from "@/components/Navbar/NavBar";



export const metadata: Metadata = {
  title: "ARIT SERVICE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
              <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
        <SidebarProvider>
        <AppSidebar />
        <main className="flex flex-col w-full">
              <Navbar />
              <div className="mx-auto mx-8 w-full h-full">{children}</div>
            </main>
      </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
